### ISSUE TITLE
KerrGeoOrbit does not include all info needed for generic Teukolsky source

### ISSUE THREAD

**Issue by znasipak** [BlackHolePerturbationToolkit/KerrGeodesics#27]
KerrGeoOrbit also needs to return $\Delta t^{(r)}$, $\Delta t^{(\theta)}$, $\Delta \phi^{(r)}$, $\Delta \phi^{(\theta)}$, and $\Upsilon_t$ to extend TeukolskyPointParticle to generic sources

**Comment by lisadrummond** [comment]
(1) It would be useful if ParallelTransport could return solutions as functions of the radial, theta and spin precession phases, rather than everything explicitly as a function of Mino time (this is useful for performing triple integration to obtain Fourier coefficients). This could  be added as an option maybe? 

(2) It would also be useful to return the MarckCarterFrame mcf(lambda) and PrecessionPhase pt\[Psi](lambda) as associations.

**Comment by MvdMeent** [comment]
@znasipak Working on it.

**Comment by barrywardell** [comment]
This was fixed in pull requests #34, #35 and #36.
